added Jenkins File and README, fixed minor issues
UladzislauHaiko/FinalSurge_Diploma_Haiko_Alekseichik pull request #10
Opened 2024-07-27 13:32 UTC by UladzislauHaiko

2024-07-27 19:53 UTC, voropa requested changes

2024-07-27 19:53 UTC, voropa commented on src/test/java/tests/WorkoutTests.java
> +//            .shoe("Dean Thomas (15.0 mi)")
Why commented?

2024-07-27 19:53 UTC, voropa commented on src/test/java/tests/LoginTests.java
> +    @TmsLink("85125") //ссылка на тесткейс
Do you really need these links here?

2024-07-28 08:29 UTC, UladzislauHaiko commented on src/test/java/tests/WorkoutTests.java
> +//            .shoe("Dean Thomas (15.0 mi)")
Forgot to uncomment.

2024-07-28 20:28 UTC, voropa approved these changes

2024-07-29 08:52 UTC, voropa requested changes

2024-07-29 08:52 UTC, voropa commented on src/test/java/tests/WorkoutTests.java
>      public void addNewRun() {
Этот тест падает с ошибкой, это так нужно для отчета или нет?
<img width="1592" alt="image" src="https://github.com/user-attachments/assets/f687d98f-0049-4b3f-b31b-7d21f44cb64f">

2024-07-29 08:52 UTC, voropa commented on src/test/java/tests/ShoesTests.java
>      public void deleteShoe() {
А где хоть какая-то проверка в этом тесте? Что он тестирует?

2024-07-29 08:52 UTC, voropa commented on src/test/java/tests/BaseTest.java
> -
Тут нет данного класса с тестом в пул реквесте, поэтому буду писать тут:
1. Почему в этом тесте нет проверки на то, что файл успешно загружен? Смысл теста на file upload - удостоверится, что файл загрузился
<img width="846" alt="image" src="https://github.com/user-attachments/assets/63082b2a-5a23-4614-9dee-59799acd50a1">

2024-07-29 08:52 UTC, voropa commented on src/test/java/tests/BaseTest.java
>      @BeforeClass(alwaysRun = true)
2. Почему тут только негативный тест на данный функционал? Тестирование любой фичи должно начинатся с позитивного сценарного теста. Да и в целом, у тебя во  фреймворке только 5 позитивных тестов, один из которых - простой логин. Добавь позитивный тест хотя бы на этот функционал с import Data
<img width="1023" alt="image" src="https://github.com/user-attachments/assets/a46b1607-b120-4bd7-ac47-98714a1d5ddd">

2024-07-29 08:52 UTC, voropa commented on src/test/java/tests/BaseTest.java
>  import org.testng.ITestContext;
Про BaseTest и BaseTEstWithoutLogin - зачем делать 2 класса и дублироват ьв них почтии одинаковый код. Можно воспользоваться насдледованием: сделать BaseTest с before / after без логина, а потом BaseTestWithLogin унаследовать от BaseTest и расширить (переопределить) в нем before метод setUp() {
super.setUp();
login();
}

2024-07-29 21:11 UTC, voropa requested changes

2024-07-29 21:11 UTC, voropa commented on src/test/java/tests/CalendarTests.java
> +        calendarPage.isActivityCardDisplayedForDay("10");
Why value 10 is hardcoded here?

2024-07-29 21:29 UTC, voropa requested changes

2024-07-29 21:29 UTC, voropa commented on src/test/java/tests/ImportDataTests.java
> +        Assert.assertTrue(calendarPage.isActivityCardDisplayedForDay("20"));
А почему тут 20? Откуда берутся эти цифры 10, 20? Почему не 103 и 507?

2024-07-29 21:33 UTC, UladzislauHaiko commented on src/test/java/tests/ImportDataTests.java
> +        Assert.assertTrue(calendarPage.isActivityCardDisplayedForDay("20"));
Цифру 10 я ставил в isActivityCardDisplayedForDay("10") потому что выше там был аплоад для 10 дня). Ок, раз используется в 2 местах, то вынес в переменную. 
Но ImportDataTests приходится хардкодить, потому что там дата внутри самого файла выставляется, а при аплоуде на юай я дату не выбираю, только сам файл

2024-07-29 21:48 UTC, voropa commented on src/test/java/tests/ImportDataTests.java
> +        Assert.assertTrue(calendarPage.isActivityCardDisplayedForDay("20"));
В такомм случае тоже вынеси ее в переменную с говорящим именем, чтобы было понятно, откуда она берется

2024-07-30 07:11 UTC, voropa approved these changes

2024-07-31 11:40 UTC, merged